Prevent skipping when player is not ready
ThePalaceProject/ios-audiobooktoolkit pull request #31
Opened 2023-01-12 21:35 UTC by mauricecarrier7

This fix introduces a cleaner solution to prevent rapid attempts to skip the player do not cause race conditions by modifying the player when it is not ready.

2023-01-16 18:33 UTC, vladimirfedorov requested changes

2023-01-16 18:33 UTC, vladimirfedorov commented on NYPLAudiobookToolkit/Player/Player.swift
> +    let playheadOffset = destinationChapter.duration - timeIntoPreviousChapter + (destinationChapter.chapterOffset ?? destinationChapter.playheadOffset)
When we skip to the previous chapter, we always end up 15 seconds to the end of it - it's probably because destinationChapter is at cursor.prev(), so it's always 0.0

2023-01-16 18:33 UTC, vladimirfedorov commented on NYPLAudiobookToolkit/Player/Player.swift
> +    let playheadOffset = destinationChapter.duration - timeIntoPreviousChapter + (destinationChapter.chapterOffset ?? destinationChapter.playheadOffset)
Also if you hold the scrubber and pull it to the left side of the screen, the player goes to the last playhead position in the previous chapter, which can be in the middle of the chapter. The same happens if you pull the scrubber to the right side of the screen, the player starts playing next chapter.  I don't think we should change the chapter if the user accidentally pulls the scrubber too far to the left of right side.

2023-01-27 04:52 UTC, mauricecarrier7 commented on NYPLAudiobookToolkit/Core/AudiobookManager.swift
> +private var waitingForPlayer: Bool = false
I do not like this solution. I think the better solution will be to convert OpenAccessPlayer to use a queue, in the same way the Findaway player does. I've created a ticket to revisit: https://www.notion.so/lyrasis/OpenAccessPlayer-Queue-player-actions-8efe44ae72d4450192cda0e94397272a

2023-01-27 16:47 UTC, vladimirfedorov approved these changes
Looks good to me

2023-01-27 16:53 UTC, merged